# https://aka.ms/yaml

# Name of the pipeline applied during run
name: Terraform-Workshop-CICD

# Trigger of the pipeline when code is checked into the repo (in this case no automatic trigger)
trigger:
  branches:
    include:
    - refs/heads/develop
    - refs/heads/release/*
    - refs/heads/hotfix/*

Parameters:

  - name: components
    displayName: 'just validate, just deploy, or both?'
    type: string
    values:
    - validate
    - deploy
    - all

stages:

  - stage: ontwikkel
    displayName: ontwikkel
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
    jobs:
    - ${{ if or(eq(parameters.components, 'infra'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: o
    - ${{ if or(eq(parameters.components, 'app'), eq(parameters.components, 'all')) }}:
      - template: /terraform-deploy.yml
        parameters:
          dtapName: o
          components: ${{ parameters.components }}

  - stage: test
    displayName: test
    dependsOn:
    - ontwikkel
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'infra'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: t
    - ${{ if or(eq(parameters.components, 'app'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: t
          components: ${{ parameters.components }}

  - stage: acceptatie
    displayName: acceptatie
    dependsOn:
    - test
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'infra'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: a
    - ${{ if or(eq(parameters.components, 'app'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: a
          components: ${{ parameters.components }}

  - stage: productie
    displayName: productie
    dependsOn:
    - acceptatie
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'infra'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: p
    - ${{ if or(eq(parameters.components, 'app'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: p
          components: ${{ parameters.components }}
