# https://aka.ms/yaml

# Name of the pipeline deploylied during run
name: Terraform-Workshop-CICD

# Trigger of the pipeline when code is checked into the repo (in this case no automatic trigger)
trigger:
  branches:
    include:
    - refs/heads/develop
    - refs/heads/release/*
    - refs/heads/hotfix/*

# Variables or variable groups defined for this pipeline to use
variables:
- group: backend_config           #tbc__ prefix

# Pool vmImage specifies which agent should be used to run this pipeline. 
# In this case the "ubuntu-latest" image is being used to run this pipeline
pool:
  vmImage: 'ubuntu-latest'

parameters:

  - name: components
    displayName: 'just validate, just deploy, or both?'
    type: string
    default: all
    values:
    - validate
    - deploy
    - all

stages:

  - stage: ontwikkel
    displayName: ontwikkel
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
    jobs:
    - ${{ if or(eq(parameters.components, 'validate'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: o
    - ${{ if or(eq(parameters.components, 'deploy'), eq(parameters.components, 'all')) }}:
      - template: /terraform-deploy.yml
        parameters:
          dtapName: o

  - stage: test
    displayName: test
    dependsOn:
    - ontwikkel
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'validate'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: t
    - ${{ if or(eq(parameters.components, 'deploy'), eq(parameters.components, 'all')) }}:
      - template: /terraform-deply.yml
        parameters:
          dtapName: t

  - stage: acceptatie
    displayName: acceptatie
    dependsOn:
    - test
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'validate'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: a
    - ${{ if or(eq(parameters.components, 'deploy'), eq(parameters.components, 'all')) }}:
      - template: /terraform-deploy.yml
        parameters:
          dtapName: a

  - stage: productie
    displayName: productie
    dependsOn:
    - acceptatie
    condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    jobs:
    - ${{ if or(eq(parameters.components, 'validate'), eq(parameters.components, 'all')) }}:
      - template: /terraform-validate.yml
        parameters:
          dtapName: p
    - ${{ if or(eq(parameters.components, 'deploy'), eq(parameters.components, 'all')) }}:
      - template: /terraform-deploy.yml
        parameters:
          dtapName: p
