
jobs:
  - job: Validate
    displayName: Validate Terraform Configuration
    steps:

    # Install specific Terraform version on the microsoft hosted agent
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terraform : Install'
      inputs:
        terraformVersion: 1.1.7
    
    # Terraform init: initialize working directory containing Terraform configuration files
    - task: TerraformTaskV2@2
      displayName: 'Terraform : Init'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/cicdautomation' # location of terraform configuration files in your repo
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(tbc__backend_service_arm)'                    # Credentials used by terraform backend to connect to the azurerm provider
        backendAzureRmResourceGroupName: '$(tbc__resource_group_name)'      # Resource group containing the storage account in your subscription
        backendAzureRmStorageAccountName: '$(tbc__storage_account_name)'    # Storage account used to store the tfstate file
        backendAzureRmContainerName: '$(tbc__storage_container_name)'             # Storage container used to store the tfstate file
        backendAzureRmKey: '$(tbc__tfstate)'                                # Name of the tfstate file
    
    # Validate Terraform syntax
    - task: TerraformTaskV2@2
      displayName: 'Terraform : Validate'
      inputs:
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/cicdautomation'